In [1]:
import torch
import torch.nn as nn
import math

In [2]:
d_head = 4
theta = 1.0 / (10000 ** (torch.arange(0, d_head, 2).float() / d_head))
print(theta)

tensor([1.0000, 0.0100])


In [5]:
max_seq_len = 8
positions = torch.arange(max_seq_len).unsqueeze(1)
print(positions)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7]])


In [6]:
freqs = positions * theta.unsqueeze(0)
print(freqs)

tensor([[0.0000, 0.0000],
        [1.0000, 0.0100],
        [2.0000, 0.0200],
        [3.0000, 0.0300],
        [4.0000, 0.0400],
        [5.0000, 0.0500],
        [6.0000, 0.0600],
        [7.0000, 0.0700]])


In [7]:
freqs_cis = torch.polar(torch.ones_like(freqs), freqs)
print(freqs_cis)

tensor([[ 1.0000+0.0000j,  1.0000+0.0000j],
        [ 0.5403+0.8415j,  0.9999+0.0100j],
        [-0.4161+0.9093j,  0.9998+0.0200j],
        [-0.9900+0.1411j,  0.9996+0.0300j],
        [-0.6536-0.7568j,  0.9992+0.0400j],
        [ 0.2837-0.9589j,  0.9988+0.0500j],
        [ 0.9602-0.2794j,  0.9982+0.0600j],
        [ 0.7539+0.6570j,  0.9976+0.0699j]])


In [ ]:
seq_len = max_seq_len